-- Eliminar tablas si existen antes de crearlas
DROP TABLE IF EXISTS INSCRIPCION;
DROP TABLE IF EXISTS CURSOESTUDIANTE;
DROP TABLE IF EXISTS ESTUDIANTE;
DROP TABLE IF EXISTS CURSOPROFESOR;
DROP TABLE IF EXISTS CURSO;
DROP TABLE IF EXISTS PROGRAMA;
DROP TABLE IF EXISTS PROFESOR;
DROP TABLE IF EXISTS FACULTAD;
DROP TABLE IF EXISTS PERSONA;

-- Crear tablas
CREATE TABLE PERSONA
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRES   CHARACTER VARYING(255),
    APELLIDOS CHARACTER VARYING(255),
    EMAIL     CHARACTER VARYING(255)
);

CREATE TABLE FACULTAD
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE    CHARACTER VARYING(255),
    DECANO_ID BIGINT REFERENCES PERSONA
);

CREATE TABLE PROFESOR
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRES      CHARACTER VARYING(255),
    APELLIDOS    CHARACTER VARYING(255),
    EMAIL        CHARACTER VARYING(255),
    TIPOCONTRATO CHARACTER VARYING(255)
);

CREATE TABLE PROGRAMA
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      CHARACTER VARYING(255),
    DURACION    BIGINT,
    FACULTAD_ID BIGINT REFERENCES FACULTAD,
    REGISTRO    DATE
);

CREATE TABLE CURSO
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    PROGRAMA_ID BIGINT REFERENCES PROGRAMA,
    ACTIVO      BOOLEAN
);

CREATE TABLE CURSOPROFESOR
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    PROFESOR_ID BIGINT REFERENCES PROFESOR,
    AÑO         INTEGER,
    SEMESTRE    INTEGER,
    CURSO_ID    BIGINT REFERENCES CURSO
);

CREATE TABLE ESTUDIANTE
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRES     CHARACTER VARYING(255),
    APELLIDOS   CHARACTER VARYING(255),
    EMAIL       CHARACTER VARYING(255),
    CODIGO      DOUBLE PRECISION,
    PROGRAMA_ID BIGINT REFERENCES PROGRAMA,
    ACTIVO      BOOLEAN,
    PROMEDIO    DOUBLE PRECISION
);

CREATE TABLE CURSOESTUDIANTE
(
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    CURSO_ID      BIGINT REFERENCES CURSO ON DELETE CASCADE,
    AÑO           INTEGER,
    SEMESTRE      INTEGER,
    ESTUDIANTE_ID BIGINT REFERENCES ESTUDIANTE ON DELETE CASCADE
);

CREATE TABLE INSCRIPCION
(
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    CURSO_ID      BIGINT NOT NULL REFERENCES CURSO ON DELETE CASCADE,
    ESTUDIANTE_ID BIGINT NOT NULL REFERENCES ESTUDIANTE ON DELETE CASCADE,
    AÑO           INTEGER NOT NULL,
    SEMESTRE      INTEGER NOT NULL
);